apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: default
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      nodeSelector:
        agentpool: arm64
      tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
        - name: service-discovery
          image: collinx0108/service-discovery:prod
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "128Mi"
              cpu: "80m"
            limits:
              memory: "384Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_APPLICATION_NAME
              value: "SERVICE-DISCOVERY"
            - name: SERVER_PORT
              value: "8761"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3 