apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: default
  labels:
    app: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      nodeSelector:
        agentpool: arm64
      tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
        - name: proxy-client
          image: collinx0108/proxy-client:prod
          ports:
            - containerPort: 8900
          resources:
            requests:
              memory: "128Mi"
              cpu: "80m"
            limits:
              memory: "384Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "proxy-client"
            - name: SPRING_APPLICATION_NAME
              value: "PROXY-CLIENT"
            - name: SERVER_PORT
              value: "8900"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8900
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8900
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config 