apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: default
  labels:
    app: proxy-client
spec:
  selector:
    app: proxy-client
  ports:
    - protocol: TCP
      port: 8900
      targetPort: 8900
  type: ClusterIP 