apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      nodeSelector:
        agentpool: arm64
      tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
        - name: order-service
          image: collinx0108/order-service:develop
          ports:
            - containerPort: 8300
          resources:
            requests:
              memory: "128Mi"
              cpu: "80m"
            limits:
              memory: "384Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "develop"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "order-service"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: "ORDER-SERVICE"
            - name: SERVER_PORT
              value: "8300"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/order-service"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:file:/data/ecommerce_dev_db;DB_CLOSE_ON_EXIT=FALSE"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.H2Dialect"
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_H2_CONSOLE_PATH
              value: "/h2-console"
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DDL_AUTO
              value: "create"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://cloud-config:9296"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
          livenessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: 8300
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: 8300
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
            - name: h2-data
              mountPath: /data
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config 
        - name: h2-data
          emptyDir: {} 