apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: default
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      nodeSelector:
        agentpool: arm64
      tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
        - name: favourite-service
          image: collinx0108/favourite-service:prod
          ports:
            - containerPort: 8800
          resources:
            requests:
              memory: "128Mi"
              cpu: "80m"
            limits:
              memory: "384Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "favourite-service"
            - name: SPRING_APPLICATION_NAME
              value: "FAVOURITE-SERVICE"
            - name: SERVER_PORT
              value: "8800"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/favourite-service"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:favouritedb"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.H2Dialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS
              value: "true"
          livenessProbe:
            httpGet:
              path: /favourite-service/actuator/health
              port: 8800
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /favourite-service/actuator/health
              port: 8800
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
            - name: favourite-data
              mountPath: /data
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config
        - name: favourite-data
          emptyDir: {} 