server:
  port: 8900

logging:
  file:
    name: src/main/resources/script/prod_log.log
    clean-history-on-start: false
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

